---
title: "dRPE mixed model"
output: html_document
date: "2026-01-07"
---

## Load packages

```{r}
library(readr)
library(dplyr)
library(tidyverse)
library(visdat)
library(easystats)
library(performance)
library(lme4)
library(emmeans)
library(mixedup)
library(broom.mixed)
library(stats)
library(sjPlot)
library(lemon)
library(ggeasy)
library(glmmTMB)
library(svglite)
library(here)

# set theme
theme_set(theme_classic())
```

### Data import and wrangling

```{r}
# load data
rpe <- read_csv(here("data", "rpe data.csv"))

# check for missing data
vis_miss(rpe)

# wrangling
# pivot longer
rpe <- pivot_longer(
  data = rpe,
  cols = S1_Gym_L:S12_FT_B,
  names_sep = "_",
  names_to = c("Number", "Mode", "Measure"),
  values_to = "Ratings"
)

# rename variables
rpe <- rpe |> rename("Session" = "Number")
rpe$Group <- rpe$Group |>
  dplyr::recode("10-sec" = "Group One", "20-sec" = "Group Two")
rpe$Mode <- rpe$Mode |>
  dplyr::recode(
    "RST" = "Repeated-Sprint Training",
    "FT" = "Soccer Training",
    "Gym" = "Gym-Based Training"
  )
rpe$Measure <- rpe$Measure |> dplyr::recode("L" = "dRPE-L", "B" = "dRPE-B")
rpe$Session <- rpe$Session |>
  dplyr::recode(
    "S1" = "1",
    "S2" = "2",
    "S3" = "3",
    "S4" = "4",
    "S5" = "5",
    "S6" = "6",
    "S7" = "7",
    "S8" = "8",
    "S9" = "9",
    "S10" = "10",
    "S11" = "11",
    "S12" = "12"
  )

# convert rpe a dataframe
rpe <- as.data.frame(rpe)

# convert predictors to factors
rpe$ID <- as.factor(rpe$ID)
rpe$Group <- as.factor(rpe$Group)
rpe$Mode <- as.factor(rpe$Mode)
rpe$Measure <- as.factor(rpe$Measure)

# relevel factors
rpe$Mode <- factor(
  rpe$Mode,
  levels = c(
    "Repeated-Sprint Training",
    "Match",
    "Soccer Training",
    "Gym-Based Training"
  )
)
# Make session numeric
rpe$Session <- as.numeric(rpe$Session)
```

### Descriptives

```{r}
#### get descriptives ----
rpe |>
  group_by(Mode) |>
  summarise(
    mean = round(mean(Ratings, na.rm = TRUE), 3),
    sd = round(sd(Ratings, na.rm = TRUE), 3),
    min = round(min(Ratings, na.rm = TRUE), 2),
    max = round(max(Ratings, na.rm = TRUE), 2),
    n = n()
  )
```

### Mixed model

```{r}
summary(
  mixed.rpe <- lmer(
    Ratings ~ Group * Mode + Measure + (1 | ID) + (1 | Session),
    data = rpe
  )
)
tab_model(mixed.rpe)

# variance decomposition
summarise_model(mixed.rpe)

# model diagnostics
# histogram
fitted.mixed.rpe <- augment(mixed.rpe)
ggplot(fitted.mixed.rpe, aes(x = .resid)) +
  geom_histogram(binwidth = 1, color = "white") # fineish..

# relationship between fitted values and residuals ----
ggplot(fitted.mixed.rpe, aes(x = .fitted, y = .resid)) +
  geom_point(aes(color = Group)) +
  geom_smooth(method = "lm") # funneling - not good

# rerun model in glmmTMB to allows variance to differ by Mode
# model non-constant variance while preserving crossed random effects
# • variances are returned on the log scale •
summary(mixed.rpe.glmm <- glmmTMB(Ratings ~ Group * Mode + Measure + 
                            (1|ID) + (1|Session), data = rpe,
                          dispformula = ~ Mode)) # allows variance to differ by Mode
tab_model(mixed.rpe.glmm)
summarise_model(mixed.rpe.glmm) 
# the residual variance is a model parameter (model predicts residual variance)
# no detectable between-player variance.
# players do not have systemtically different intercepts after accounting for Mode
# sessions differed as players tend to report higher or lower RPEs in certain sessions
# residual variance differs by Mode (see below)
# so, variance structure explained by session and mode specific variability.

# check residuals - funeling now gone due to model respecification
plot(predict(mixed.rpe.glmm),
     resid(mixed.rpe.glmm, type = "pearson"))
# successfully modelling of the non-constant variance observed by Mode

# get mode SD's
(disp_est <- summary(mixed.rpe.glmm)$coefficients$disp[, "Estimate"]) # extract
# match and gym lower than RST, soccer training higher
(log_var <- disp_est[1] + c(0, disp_est[-1])) # get variance, compare to intercept
(sd_mode <- sqrt(exp(log_var))) # convert to SD's

# get estimated marginal means and pairwise contrasts
(est <- emmeans(mixed.rpe.glmm, ~ Group | Mode))
(pairs <- summary(contrast(est, "pairwise"), infer = TRUE))

# manual bonferroni CI adjustment for these 4 comparisons
(df <- pairs$df) # set df
(m <- nrow(pairs)) # set number of contrasts
(alpha <- 0.05) # set alpha
(crit <- qt(1 - alpha / (2 * m), df)) # get critical t per row

(model.bonf <- pairs |>
  mutate(
    lower.CL.bonf = estimate - crit * SE,
    upper.CL.bonf = estimate + crit * SE,
    p.value.bonf = p.adjust(p.value, method = "bonferroni")
  ) |>
  mutate(across(
    c(estimate, SE, df, lower.CL.bonf, upper.CL.bonf, p.value.bonf),
    ~ round(., 3)
  )) |>
  select(
    Mode,
    contrast,
    estimate,
    SE,
    df,
    lower.CL.bonf,
    upper.CL.bonf,
    p.value.bonf
  ))

# save results for plotting in figures.Rmd
saveRDS(model.bonf, here("data", "rpe_contrasts.rds"))
```
