---
title: "figures"
output: html_document
date: "2026-01-07"
---

### Load packages

```{r}
library(readr)
library(dplyr)
library(tidyverse)
library(ggeasy)
library(visdat)
library(lemon)
library(ggdist)
library(here)

# set plot theme
theme_set(theme_classic(base_size=18, base_family="sans"))
```

### RPE plot

#### Load data, check for missing values, and wrangle.

```{r}
rpe <- read_csv(here("data", "rpe data.csv"))

# check for missing data
vis_miss(rpe)

# pivot longer 
rpe <- pivot_longer(data = rpe,
                    cols = S1_Gym_L:S12_FT_B,
                    names_sep = "_",
                    names_to = c("Number", 
                                 "Mode", 
                                 "Measure"),
                    values_to = "Ratings")

# rename variables
rpe <- rpe |> rename("Session" = "Number")
rpe$Group <- rpe$Group |> dplyr::recode("10-sec" = "Group 1", "20-sec" = "Group 2")
rpe$Mode <- rpe$Mode |> dplyr::recode ("RST" = "Repeated-Sprint Training",
                                      "FT" = "Soccer Training",
                                      "Gym" = "Gym-Based Training")
rpe$Measure <- rpe$Measure |> dplyr::recode("L" = "dRPE-L", "B" = "dRPE-B")
rpe$Session <- rpe$Session |> dplyr::recode("S1" = "1", "S2" = "2", "S3" = "3",
                                          "S4" = "4", "S5" = "5", "S6" = "6",
                                          "S7" = "7", "S8" = "8", "S9" = "9",
                                          "S10" = "10", "S11" = "11", "S12" = "12")

# convert rpe a dataframe
rpe <- as.data.frame(rpe)

# convert predictors to factors
rpe$ID <- as.factor(rpe$ID)
rpe$Group <- as.factor(rpe$Group)
rpe$Mode <- as.factor(rpe$Mode)
rpe$Measure <- as.factor(rpe$Measure)

# relevel factors
rpe$Mode <- factor(rpe$Mode, levels = c("Repeated-Sprint Training", "Match", 
                                        "Soccer Training", 
                                        "Gym-Based Training"))
# Make session numeric 
rpe$Session <- as.numeric(rpe$Session)
```

#### Plot and save

```{r}
rpe |>
  ggplot(aes(x = Session, y = Ratings, col = Mode)) +
  geom_jitter(size = 2, height = 0.05, alpha = 0.25) +
  geom_smooth(aes(fill = Mode), method = 'lm', se = F, linewidth = 1.5) +
  scale_fill_manual(values = c("red", "blue", "orange", "orchid")) +
  scale_colour_manual(values = c("red", "blue", "orange", "orchid")) +
  scale_y_continuous(limits = c(0, 100), breaks = seq(from = 0, to = 100, by = 10)) +
  scale_x_continuous(limits = c(1, 12), breaks = seq(from = 1, to = 12, by = 1)) +
  labs(y = "Ratings (AU)", x = "Session Number") +
  theme_classic() +
  facet_wrap(~Group) +
  easy_all_text_color("black") +
  theme(legend.text = element_text(size=18), legend.position = "top", 
        legend.title = element_text(size=18), legend.box.spacing = unit(0, "pt"),
        strip.background.x = element_rect(fill='cornsilk', colour = "black"),
        strip.text.x = element_text(colour = "black"),
        strip.text = element_text(size=18),
        axis.line = element_line(linewidth = 0.5),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size = 18),
        axis.title.x = element_text(size = 18),
        axis.text.y = element_text(size = 18), axis.title.y = element_text(size = 18)) +
  coord_capped_cart(left = capped_vertical("both"), bottom = capped_horisontal("both"))

# Save figure
# Output format: SVG (scalable vector graphics). For PNG output, change extension to .png
ggsave(here("figures", "figure 3.svg"), dpi = 300, width = 30, height = 15, units = "cm")
```

### Raincloud plots

#### Load data

```{r}
data <- read_csv(here("data", "ANCOVA Final Long.csv"))
data <- data |>
  mutate(across(c(Group, ID, Timeline, Test), as_factor))

data$Group <- data$Group |>
  dplyr::case_match("10-sec" ~ "Group 1", "20-sec" ~ "Group 2")
data$Group <- factor(data$Group, levels = c("Group 1", "Group 2"))
```

#### Plot and save

```{r}
custom_labels <- c(
  "Time_10m" = "10 m Sprint Time (sec)",
  "Time_20m" = "20 m Sprint Time (sec)",
  "Time_40m" = "40 m Sprint Time (sec)",
  "Max_Velocity" = "VMax (m·s⁻¹)",
  "MAS" = "MAS (m·s⁻¹)",
  "CMJH" = "CMJ (cm)"
)

cbp <- c("#C84E00", "#012169")

data_positioned <- data |>
  mutate(
    x_points = case_when(
      Timeline == "Pre" & Group == "Group 1" ~ 0.7,
      Timeline == "Pre" & Group == "Group 2" ~ 0.7,
      Timeline == "Post" & Group == "Group 1" ~ 2.3,
      Timeline == "Post" & Group == "Group 2" ~ 2.3
    ),
    x_boxes = case_when(
      Timeline == "Pre" & Group == "Group 1" ~ 0.15,
      Timeline == "Pre" & Group == "Group 2" ~ 0.45,
      Timeline == "Post" & Group == "Group 1" ~ 2.55,
      Timeline == "Post" & Group == "Group 2" ~ 2.85
    ),
    x_violins = case_when(
      Timeline == "Pre" & Group == "Group 1" ~ 0,
      Timeline == "Pre" & Group == "Group 2" ~ 0,
      Timeline == "Post" & Group == "Group 1" ~ 3,
      Timeline == "Post" & Group == "Group 2" ~ 3
    )
  )

mean_data <- data |>
  group_by(Test, Group, Timeline) |>
  summarise(mean_value = mean(Value, na.rm = TRUE)) |>
  ungroup() %>%
  # Add the same x-coordinates used for the boxplots
  mutate(
    x_boxes = case_when(
      Timeline == "Pre" & Group == "Group 1" ~ 0.9,
      Timeline == "Pre" & Group == "Group 2" ~ 0.9,
      Timeline == "Post" & Group == "Group 1" ~ 2.1,
      Timeline == "Post" & Group == "Group 2" ~ 2.1
    )
  )

pre_post_plot_final <- data_positioned |>
  ggplot(aes(x = Timeline, y = Value)) +
  
  stat_slab(
    aes(
      x = x_violins,
      fill = Group,
      side = ifelse(Timeline == "Pre", "left", "right")
    ),
    alpha = 0.4,
    color = NA,
    scale = 0.8,
    normalize = "panels"
  ) +
  
  geom_line(
    aes(x = x_points, group = ID, color = Group),
    alpha = 0.2,
    linewidth = 0.8
  ) +
  
  geom_boxplot(
    aes(x = x_boxes, fill = Group, group = interaction(Timeline, Group)),
    alpha = 0.6,
    width = 0.3,
    outlier.shape = NA,
    color = "black",
    linewidth = 0.5
  ) +
  
  geom_line(
    data = mean_data,
    aes(x = x_boxes, y = mean_value, group = Group, color = Group),
    linewidth = 1.5,
    alpha = 0.6
  ) +
  
  geom_point(
    data = mean_data,
    aes(x = x_boxes, y = mean_value, fill = Group),
    shape = 22,
    alpha = 0.7,
    color = "black",
    size = 6,
    stroke = 0.8
  ) +
  
  geom_point(
    aes(x = x_points, color = Group, fill = Group),
    alpha = 0.5,
    size = 2.5,
    shape = 21,
    stroke = 0.3
  ) +
  
  facet_wrap(
    ~Test,
    scales = "free_y",
    labeller = labeller(Test = custom_labels),
    strip.position = "left"
  ) +
  
  theme_classic(base_size = 25) +
  coord_capped_cart(
    left = capped_vertical("both"),
    bottom = capped_horizontal("both")
  ) +
  
  labs(title = "", x = "", y = "") +
  
  scale_fill_manual(
    values = c(
      "Group 1" = "#C84E00",
      "Group 2" = "#012169"
    )
  ) +
  
  scale_colour_manual(
    values = c("Group 1" = "#C84E00", "Group 2" = "#012169")
  ) +
  
  scale_x_continuous(
    breaks = c(0, 3),
    labels = c("Pre", "Post")
  ) +
  
  theme(legend.key.size = unit(1, "cm")) +
  theme(strip.text = element_text(face = "plain")) +
  theme(legend.position = "top") +
  theme(
    strip.placement = "outside",
    strip.background = element_blank()
  )

pre_post_plot_final

# Save figure
# Output format: SVG (scalable vector graphics). For PNG output, change extension to .png
ggsave(here("figures", "figure 4.svg"), dpi = 300, width = 40, height = 25, units = "cm")
```
